// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import "fyne.io/fyne/v2"

var resourceAppEnv = &fyne.StaticResource{
	StaticName: "app.env",
	StaticContent: []byte(
		"PORT=3000\nFREQUENCY=1\nENDPOINT=\"https://google.com\"\nDIRECTORY=\"/Users/macbookpro/Documents/savana\""),
}
